exports.productList = [
    {   id:1,
        name: 'Full Chicken',
        description: 'full frozen chicken',
        tag: 'fullchicken',
        price: 15,
        inCart: 0,
        image: '/images/fullchicken.jpg'
    },
    {   id:2,
        name: 'Turkey Wings',
        description: '3 pieces of frozen turkey wings',
        tag: 'turkeywings',
        price: 25,
        inCart: 0,
        image: '/images/turkeywings.jpg'
    },
    {   id:3,
        name: 'Smoked Fish',
        description: '3 pieces of smoked fish',
        tag: 'smokedfish',
        price: 15,
        inCart: 0,
        image: '/images/smokedfish.jpg'
    },
    {   id:4,
        name: 'Dried Snails',
        description: 'One pack of dried snails',
        tag: 'driedsnails',
        price: 100,
        inCart: 0,
        image: '/images/driedsnails.jpg'
    },
    {   id:5,
        name: 'Ponmo x3 Pcs',
        description: 'Three pieces of cowskin (ponmo)',        
        tag: 'ponmo',
        price: 20,
        inCart: 0,
        image: '/images/ponmo.jpg'
    },
    {   id:6,
        name:  'Panla Fish (Pack of 3)',
        description: 'Three pieces of panla fish',
        tag: 'panla',
        price: 15,
        inCart: 0,
        image: '/images/panla.jpg'
    },
    {   id:7,
        name: 'Kolaq Alagbo',
        description: 'One plastic bottle of Kolaq Alagbo',
        tag: 'kolaqalagbo',
        price: 20,
        inCart: 0,
        image: '/images/kolaqalagbo.jpg'
    },
    {   id:8,
        name: 'Jekanmo Herbal',
        description: 'One plastic bottle of Jekanmo',
        tag: 'jekanmo',
        price: 10,
        inCart: 0,
        image: '/images/jekanmo.jpg'
    },
    {   id:9,
        name: 'Confam bitters',
        description: 'One plastic bottle of Confam bitters',
        tag: 'confambitters',
        price: 20,
        inCart: 0,
        image: '/images/confambitters.jpg'
    },
    {   id:10,
        name: 'Natural Herbs',
        description: 'A bunch of herbs',
        tag: 'herbs',
        price: 20,
        inCart: 0,
        image: '/images/herbs.jpg'
    },
    {   id:11,
        name: 'Origin Sachet',
        description: 'One plastic bottle of Origin',
        tag: 'originsachet',
        price: 15,
        inCart: 0,
        image: '/images/originsachet.jpg'
    },
    {   id:12,
        name: 'Action Bitters',
        description: 'One plastic bottle of Action bitters',
        tag: 'actionbitters',
        price: 15,
        inCart: 0,
        image: '/images/actionbitters.jpg'
    }
]